// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ProGM_CharAnimations","status":true,"description":"Allows to run n-frames animations on characters on-demand.","parameters":{}}
];
